version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F anything
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/myapp
    environment:
      MONGODB_URL: mongodb://mongodb:27017/transfers
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
