version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F anything
    environment:
      MONGODB_URI: mongodb://mongodb:27017/transfers
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/myapp
    depends_on:
      - mongodb
    networks:
      - default

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: transfers
    networks:
      - default

networks:
  default:
    driver: bridge