version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F anything
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/myapp
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: notasecret